name: ponto_taxi_df
description: "Aplicativo para cadastramento de pontos de taxi no Distrito Federal"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 #icones do iOS
  flutter_map: ^8.1.1 #mapa padrão do flutter
  latlong2: ^0.9.1 #Latitude e Longitude
  curved_navigation_bar: ^1.0.6 #barra de navegação inferior com animação
  flutter_speed_dial: ^7.0.0 #submenu com a barra de navegação
  provider: ^6.1.5 #prover o 'estado' do app
  vector_map_tiles: ^9.0.0-beta.8
  mask_text_input_formatter: ^2.9.0
  shared_preferences: ^2.5.3
  geolocator: ^14.0.1
  audioplayers: ^6.5.0
  flutter_confetti: ^0.5.1
  image_picker: ^1.1.0
  path_provider: ^2.1.2
  path: ^1.9.0
  shimmer: ^3.0.0
  flutter_map_cancellable_tile_provider: ^3.1.1
  image_picker_web: ^4.0.0
  auto_size_text: ^3.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.16.0
  build_runner: ^2.4.8
  
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/imagessemob.webp
    - assets/images/icon_user.png
    - assets/outros/audio.mp3
    - assets/images/bus_stop_azul.webp
    - assets/images/bus_stop_verde.webp
    - assets/images/gdf.png
    - assets/fonts/OpenSans/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic